spring:
  application:
   name: Expense_Management
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/wipro_Capstone
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
     hibernate:
      format_sql: true
logging:
 level:
  org:
   hibernate:
    SQL: DEBUG
    type:
     descriptor:
      sql:
       BasicBinder: TRACE